server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
      defualt_schema: test

    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
        format_sql: true
        use_sql_comments: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgre-db.cfh61qv9x1da.us-west-2.rds.amazonaws.com:5432/postgre_db
    username: postgres
    password: adminadmin01

#logging:
#  level:
#    org:
#      hibernate:
#        type: trace




