server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
      defualt_schema: test
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
        format_sql: true
        use_sql_comments: true

  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:postgresql://postgre-db.cfh61qv9x1da.us-west-2.rds.amazonaws.com:5432/postgre_db
    username: postgres
    password: adminadmin01

#logging:
#   level:
#    org:
#      hibernate:
#        type: trace


logging:
  level:
    com:
      zaxxer:
        hikari: off
    javax:
      sql:
        DataSource: OFF
    jdbc:
      audit: OFF
      result: off

      result-settable: INFO  #SQL 결과 데이터 Table을 로그로 남긴다.
      sql only: off     #SQL만 로그로 남긴다.
      sliding: debug    #SQL과 소요시간을 표기한다.
      connection : OFF  # 커넥션 확인가능
    org:
      hibernate:
        SQL: off
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

mybatis:
  mapper-locations: classpath:mapper/**.xml

